# Generated by Django 5.0.4 on 2024-04-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventspace', '0005_alter_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
