# Generated by Django 5.0.4 on 2024-04-08 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspace', '0006_remove_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 7, 22, 51, 33, 939412)),
        ),
    ]
