# Generated by Django 5.0.4 on 2024-04-08 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspace', '0007_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 8, 4, 52, 39, 818733, tzinfo=datetime.timezone.utc)),
        ),
    ]
