# Generated by Django 5.0.4 on 2024-04-08 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspace', '0009_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 8, 4, 55, 18, 782187, tzinfo=datetime.timezone.utc)),
        ),
    ]
