# Generated by Django 5.0.4 on 2024-04-09 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspace', '0014_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(0, 28, 32, 178954), verbose_name='Time'),
        ),
    ]
