# Generated by Django 5.0.4 on 2024-04-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspace', '0017_remove_event_time_event_endtime_event_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=None),
        ),
    ]
