# Generated by Django 5.0.4 on 2024-04-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspace', '0021_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
